version: "2"

services:
  ss_ap:
    image: yangxuan8282/ss-client
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - SS_SERVER_IP=
      - SS_SERVER_PORT=443
      - SS_METHOD=chacha20-ietf-poly1305
      - SS_PASSWD=
      - SS_TIMEOUT=300
      - SS_LOCAL_PORT=1080 
      - SS_ARGS='--plugin obfs-local --plugin-opts "obfs=tls;obfs-host=www.yahoo.com"'

