version: "2"

services:
  ss-client:
    #for amd64:
    #image: yangxuan8282/ss-client:amd64
    image: yangxuan8282/ss-client
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - SS_SERVER_IP=
      - SS_SERVER_PORT=7443
      - SS_METHOD=chacha20
      - SS_PASSWD=
      - SS_LOCAL_PORT= 
