version: "2"

services:
  ss-server:
    image: yangxuan8282/ss-server
    restart: "always"
    ports:
      - "7443:8388"
      - "7443:8388/udp"
    environment:
      - SS_SERVER_PORT=8388
      - SS_PASSWD=
      - SS_METHOD=chacha20-ietf-poly1305
      - SS_ARGS=--plugin obfs-server --plugin-opts "obfs=tls"

